package com.falaisia.ship.eventreporting2.domain;

import static com.falaisia.ship.eventreporting2.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BunkerReceivedNoteLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBunkerReceivedNoteLineAllPropertiesEquals(BunkerReceivedNoteLine expected, BunkerReceivedNoteLine actual) {
        assertBunkerReceivedNoteLineAutoGeneratedPropertiesEquals(expected, actual);
        assertBunkerReceivedNoteLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBunkerReceivedNoteLineAllUpdatablePropertiesEquals(
        BunkerReceivedNoteLine expected,
        BunkerReceivedNoteLine actual
    ) {
        assertBunkerReceivedNoteLineUpdatableFieldsEquals(expected, actual);
        assertBunkerReceivedNoteLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBunkerReceivedNoteLineAutoGeneratedPropertiesEquals(
        BunkerReceivedNoteLine expected,
        BunkerReceivedNoteLine actual
    ) {
        assertThat(actual)
            .as("Verify BunkerReceivedNoteLine auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBunkerReceivedNoteLineUpdatableFieldsEquals(BunkerReceivedNoteLine expected, BunkerReceivedNoteLine actual) {
        assertThat(actual)
            .as("Verify BunkerReceivedNoteLine relevant properties")
            .satisfies(a ->
                assertThat(a.getQuantity()).as("check quantity").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getQuantity())
            )
            .satisfies(a -> assertThat(a.getUnitOfMeasure()).as("check unitOfMeasure").isEqualTo(expected.getUnitOfMeasure()))
            .satisfies(a ->
                assertThat(a.getLowerCalorificValue())
                    .as("check lowerCalorificValue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getLowerCalorificValue())
            )
            .satisfies(a ->
                assertThat(a.getSulphurContent())
                    .as("check sulphurContent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getSulphurContent())
            )
            .satisfies(a ->
                assertThat(a.getDensity()).as("check density").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getDensity())
            )
            .satisfies(a ->
                assertThat(a.getViscosity()).as("check viscosity").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getViscosity())
            )
            .satisfies(a ->
                assertThat(a.getWaterContent())
                    .as("check waterContent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getWaterContent())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBunkerReceivedNoteLineUpdatableRelationshipsEquals(
        BunkerReceivedNoteLine expected,
        BunkerReceivedNoteLine actual
    ) {
        assertThat(actual)
            .as("Verify BunkerReceivedNoteLine relationships")
            .satisfies(a -> assertThat(a.getBunkerReceivedNote()).as("check bunkerReceivedNote").isEqualTo(expected.getBunkerReceivedNote())
            )
            .satisfies(a -> assertThat(a.getFuelType()).as("check fuelType").isEqualTo(expected.getFuelType()));
    }
}
