package com.falaisia.ship.eventreporting2.domain;

import static com.falaisia.ship.eventreporting2.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class BunkerReceivedNoteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBunkerReceivedNoteAllPropertiesEquals(BunkerReceivedNote expected, BunkerReceivedNote actual) {
        assertBunkerReceivedNoteAutoGeneratedPropertiesEquals(expected, actual);
        assertBunkerReceivedNoteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBunkerReceivedNoteAllUpdatablePropertiesEquals(BunkerReceivedNote expected, BunkerReceivedNote actual) {
        assertBunkerReceivedNoteUpdatableFieldsEquals(expected, actual);
        assertBunkerReceivedNoteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBunkerReceivedNoteAutoGeneratedPropertiesEquals(BunkerReceivedNote expected, BunkerReceivedNote actual) {
        assertThat(actual)
            .as("Verify BunkerReceivedNote auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBunkerReceivedNoteUpdatableFieldsEquals(BunkerReceivedNote expected, BunkerReceivedNote actual) {
        assertThat(actual)
            .as("Verify BunkerReceivedNote relevant properties")
            .satisfies(a ->
                assertThat(a.getDocumentDateAndTime())
                    .as("check documentDateAndTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getDocumentDateAndTime())
            )
            .satisfies(a ->
                assertThat(a.getDocumentDisplayNumber()).as("check documentDisplayNumber").isEqualTo(expected.getDocumentDisplayNumber())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBunkerReceivedNoteUpdatableRelationshipsEquals(BunkerReceivedNote expected, BunkerReceivedNote actual) {
        assertThat(actual)
            .as("Verify BunkerReceivedNote relationships")
            .satisfies(a -> assertThat(a.getVoyage()).as("check voyage").isEqualTo(expected.getVoyage()));
    }
}
