package com.falaisia.ship.eventreporting2.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClassificationSocietyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassificationSocietyAllPropertiesEquals(ClassificationSociety expected, ClassificationSociety actual) {
        assertClassificationSocietyAutoGeneratedPropertiesEquals(expected, actual);
        assertClassificationSocietyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassificationSocietyAllUpdatablePropertiesEquals(
        ClassificationSociety expected,
        ClassificationSociety actual
    ) {
        assertClassificationSocietyUpdatableFieldsEquals(expected, actual);
        assertClassificationSocietyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassificationSocietyAutoGeneratedPropertiesEquals(
        ClassificationSociety expected,
        ClassificationSociety actual
    ) {
        assertThat(actual)
            .as("Verify ClassificationSociety auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassificationSocietyUpdatableFieldsEquals(ClassificationSociety expected, ClassificationSociety actual) {
        assertThat(actual)
            .as("Verify ClassificationSociety relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClassificationSocietyUpdatableRelationshipsEquals(
        ClassificationSociety expected,
        ClassificationSociety actual
    ) {
        // empty method
    }
}
