package com.falaisia.ship.eventreporting2.domain;

import static com.falaisia.ship.eventreporting2.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ConsumptionLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumptionLineAllPropertiesEquals(ConsumptionLine expected, ConsumptionLine actual) {
        assertConsumptionLineAutoGeneratedPropertiesEquals(expected, actual);
        assertConsumptionLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumptionLineAllUpdatablePropertiesEquals(ConsumptionLine expected, ConsumptionLine actual) {
        assertConsumptionLineUpdatableFieldsEquals(expected, actual);
        assertConsumptionLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumptionLineAutoGeneratedPropertiesEquals(ConsumptionLine expected, ConsumptionLine actual) {
        assertThat(actual)
            .as("Verify ConsumptionLine auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumptionLineUpdatableFieldsEquals(ConsumptionLine expected, ConsumptionLine actual) {
        assertThat(actual)
            .as("Verify ConsumptionLine relevant properties")
            .satisfies(a ->
                assertThat(a.getQuantity()).as("check quantity").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getQuantity())
            )
            .satisfies(a -> assertThat(a.getUnitOfMeasure()).as("check unitOfMeasure").isEqualTo(expected.getUnitOfMeasure()))
            .satisfies(a ->
                assertThat(a.getCo2EmissionSourceTypeCode())
                    .as("check co2EmissionSourceTypeCode")
                    .isEqualTo(expected.getCo2EmissionSourceTypeCode())
            )
            .satisfies(a ->
                assertThat(a.getLowerCalorificValue())
                    .as("check lowerCalorificValue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getLowerCalorificValue())
            )
            .satisfies(a ->
                assertThat(a.getSulphurContent())
                    .as("check sulphurContent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getSulphurContent())
            )
            .satisfies(a ->
                assertThat(a.getDensity()).as("check density").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getDensity())
            )
            .satisfies(a ->
                assertThat(a.getViscosity()).as("check viscosity").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getViscosity())
            )
            .satisfies(a ->
                assertThat(a.getWaterContent())
                    .as("check waterContent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getWaterContent())
            )
            .satisfies(a -> assertThat(a.getPortActivityCode()).as("check portActivityCode").isEqualTo(expected.getPortActivityCode()))
            .satisfies(a -> assertThat(a.getDiffCriterionCode()).as("check diffCriterionCode").isEqualTo(expected.getDiffCriterionCode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumptionLineUpdatableRelationshipsEquals(ConsumptionLine expected, ConsumptionLine actual) {
        assertThat(actual)
            .as("Verify ConsumptionLine relationships")
            .satisfies(a -> assertThat(a.getEventReport()).as("check eventReport").isEqualTo(expected.getEventReport()))
            .satisfies(a -> assertThat(a.getFuelType()).as("check fuelType").isEqualTo(expected.getFuelType()));
    }
}
