package com.falaisia.ship.eventreporting2.domain;

import static com.falaisia.ship.eventreporting2.domain.AssertUtils.bigDecimalCompareTo;
import static com.falaisia.ship.eventreporting2.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class EventReportAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventReportAllPropertiesEquals(EventReport expected, EventReport actual) {
        assertEventReportAutoGeneratedPropertiesEquals(expected, actual);
        assertEventReportAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventReportAllUpdatablePropertiesEquals(EventReport expected, EventReport actual) {
        assertEventReportUpdatableFieldsEquals(expected, actual);
        assertEventReportUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventReportAutoGeneratedPropertiesEquals(EventReport expected, EventReport actual) {
        assertThat(actual)
            .as("Verify EventReport auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventReportUpdatableFieldsEquals(EventReport expected, EventReport actual) {
        assertThat(actual)
            .as("Verify EventReport relevant properties")
            .satisfies(a ->
                assertThat(a.getDocumentDateAndTime())
                    .as("check documentDateAndTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getDocumentDateAndTime())
            )
            .satisfies(a ->
                assertThat(a.getSpeedGps()).as("check speedGps").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSpeedGps())
            )
            .satisfies(a ->
                assertThat(a.getDocumentDisplayNumber()).as("check documentDisplayNumber").isEqualTo(expected.getDocumentDisplayNumber())
            )
            .satisfies(a -> assertThat(a.getLeg()).as("check leg").isEqualTo(expected.getLeg()))
            .satisfies(a ->
                assertThat(a.getDistanceTravelled())
                    .as("check distanceTravelled")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDistanceTravelled())
            )
            .satisfies(a ->
                assertThat(a.getHoursUnderway())
                    .as("check hoursUnderway")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getHoursUnderway())
            )
            .satisfies(a -> assertThat(a.getEventStatus()).as("check eventStatus").isEqualTo(expected.getEventStatus()))
            .satisfies(a -> assertThat(a.getLoadingCondition()).as("check loadingCondition").isEqualTo(expected.getLoadingCondition()))
            .satisfies(a ->
                assertThat(a.getCargoCarried())
                    .as("check cargoCarried")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCargoCarried())
            )
            .satisfies(a ->
                assertThat(a.getCoordinatesLatitude()).as("check coordinatesLatitude").isEqualTo(expected.getCoordinatesLatitude())
            )
            .satisfies(a ->
                assertThat(a.getCoordinatesLongitude()).as("check coordinatesLongitude").isEqualTo(expected.getCoordinatesLongitude())
            )
            .satisfies(a -> assertThat(a.getShipsHeading()).as("check shipsHeading").isEqualTo(expected.getShipsHeading()))
            .satisfies(a -> assertThat(a.getBeaufortNo()).as("check beaufortNo").isEqualTo(expected.getBeaufortNo()))
            .satisfies(a -> assertThat(a.getWeatherCondition()).as("check weatherCondition").isEqualTo(expected.getWeatherCondition()))
            .satisfies(a -> assertThat(a.getSwell()).as("check swell").isEqualTo(expected.getSwell()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventReportUpdatableRelationshipsEquals(EventReport expected, EventReport actual) {
        assertThat(actual)
            .as("Verify EventReport relationships")
            .satisfies(a -> assertThat(a.getVoyage()).as("check voyage").isEqualTo(expected.getVoyage()));
    }
}
