package com.falaisia.ship.eventreporting2.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FlagAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlagAllPropertiesEquals(Flag expected, Flag actual) {
        assertFlagAutoGeneratedPropertiesEquals(expected, actual);
        assertFlagAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlagAllUpdatablePropertiesEquals(Flag expected, Flag actual) {
        assertFlagUpdatableFieldsEquals(expected, actual);
        assertFlagUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlagAutoGeneratedPropertiesEquals(Flag expected, Flag actual) {
        assertThat(actual)
            .as("Verify Flag auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlagUpdatableFieldsEquals(Flag expected, Flag actual) {
        assertThat(actual)
            .as("Verify Flag relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFlagUpdatableRelationshipsEquals(Flag expected, Flag actual) {
        // empty method
    }
}
