package com.falaisia.ship.eventreporting2.domain;

import static com.falaisia.ship.eventreporting2.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class FuelEuRegulationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFuelEuRegulationAllPropertiesEquals(FuelEuRegulation expected, FuelEuRegulation actual) {
        assertFuelEuRegulationAutoGeneratedPropertiesEquals(expected, actual);
        assertFuelEuRegulationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFuelEuRegulationAllUpdatablePropertiesEquals(FuelEuRegulation expected, FuelEuRegulation actual) {
        assertFuelEuRegulationUpdatableFieldsEquals(expected, actual);
        assertFuelEuRegulationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFuelEuRegulationAutoGeneratedPropertiesEquals(FuelEuRegulation expected, FuelEuRegulation actual) {
        assertThat(actual)
            .as("Verify FuelEuRegulation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFuelEuRegulationUpdatableFieldsEquals(FuelEuRegulation expected, FuelEuRegulation actual) {
        assertThat(actual)
            .as("Verify FuelEuRegulation relevant properties")
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()))
            .satisfies(a -> assertThat(a.getCo2Gwp()).as("check co2Gwp").isEqualTo(expected.getCo2Gwp()))
            .satisfies(a -> assertThat(a.getMethaneGwp()).as("check methaneGwp").isEqualTo(expected.getMethaneGwp()))
            .satisfies(a -> assertThat(a.getNitrousGwp()).as("check nitrousGwp").isEqualTo(expected.getNitrousGwp()))
            .satisfies(a ->
                assertThat(a.getTargetIntensity())
                    .as("check targetIntensity")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTargetIntensity())
            )
            .satisfies(a ->
                assertThat(a.getBaselineIntensity())
                    .as("check baselineIntensity")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBaselineIntensity())
            )
            .satisfies(a ->
                assertThat(a.getReductionFactorPercent())
                    .as("check reductionFactorPercent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getReductionFactorPercent())
            )
            .satisfies(a ->
                assertThat(a.getVlsfoEnergyContentPerTonMj())
                    .as("check vlsfoEnergyContentPerTonMj")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getVlsfoEnergyContentPerTonMj())
            )
            .satisfies(a ->
                assertThat(a.getVlsfoPenaltyEurPerTon())
                    .as("check vlsfoPenaltyEurPerTon")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getVlsfoPenaltyEurPerTon())
            )
            .satisfies(a ->
                assertThat(a.getEnergyAllowanceMultiplier())
                    .as("check energyAllowanceMultiplier")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getEnergyAllowanceMultiplier())
            )
            .satisfies(a ->
                assertThat(a.getNonBioFuelRewardFactor())
                    .as("check nonBioFuelRewardFactor")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getNonBioFuelRewardFactor())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFuelEuRegulationUpdatableRelationshipsEquals(FuelEuRegulation expected, FuelEuRegulation actual) {
        // empty method
    }
}
