package com.falaisia.ship.eventreporting2.domain;

import static com.falaisia.ship.eventreporting2.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class FuelTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFuelTypeAllPropertiesEquals(FuelType expected, FuelType actual) {
        assertFuelTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertFuelTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFuelTypeAllUpdatablePropertiesEquals(FuelType expected, FuelType actual) {
        assertFuelTypeUpdatableFieldsEquals(expected, actual);
        assertFuelTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFuelTypeAutoGeneratedPropertiesEquals(FuelType expected, FuelType actual) {
        assertThat(actual)
            .as("Verify FuelType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFuelTypeUpdatableFieldsEquals(FuelType expected, FuelType actual) {
        assertThat(actual)
            .as("Verify FuelType relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getFuelTypeCode()).as("check fuelTypeCode").isEqualTo(expected.getFuelTypeCode()))
            .satisfies(a ->
                assertThat(a.getCarbonFactory())
                    .as("check carbonFactory")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCarbonFactory())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFuelTypeUpdatableRelationshipsEquals(FuelType expected, FuelType actual) {
        // empty method
    }
}
