package com.falaisia.ship.eventreporting2.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MachineryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineryAllPropertiesEquals(Machinery expected, Machinery actual) {
        assertMachineryAutoGeneratedPropertiesEquals(expected, actual);
        assertMachineryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineryAllUpdatablePropertiesEquals(Machinery expected, Machinery actual) {
        assertMachineryUpdatableFieldsEquals(expected, actual);
        assertMachineryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineryAutoGeneratedPropertiesEquals(Machinery expected, Machinery actual) {
        assertThat(actual)
            .as("Verify Machinery auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineryUpdatableFieldsEquals(Machinery expected, Machinery actual) {
        assertThat(actual)
            .as("Verify Machinery relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineryUpdatableRelationshipsEquals(Machinery expected, Machinery actual) {
        assertThat(actual)
            .as("Verify Machinery relationships")
            .satisfies(a -> assertThat(a.getShip()).as("check ship").isEqualTo(expected.getShip()));
    }
}
