package com.falaisia.ship.eventreporting2.domain;

import static com.falaisia.ship.eventreporting2.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class MachineryOperationLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineryOperationLineAllPropertiesEquals(MachineryOperationLine expected, MachineryOperationLine actual) {
        assertMachineryOperationLineAutoGeneratedPropertiesEquals(expected, actual);
        assertMachineryOperationLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineryOperationLineAllUpdatablePropertiesEquals(
        MachineryOperationLine expected,
        MachineryOperationLine actual
    ) {
        assertMachineryOperationLineUpdatableFieldsEquals(expected, actual);
        assertMachineryOperationLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineryOperationLineAutoGeneratedPropertiesEquals(
        MachineryOperationLine expected,
        MachineryOperationLine actual
    ) {
        assertThat(actual)
            .as("Verify MachineryOperationLine auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineryOperationLineUpdatableFieldsEquals(MachineryOperationLine expected, MachineryOperationLine actual) {
        assertThat(actual)
            .as("Verify MachineryOperationLine relevant properties")
            .satisfies(a ->
                assertThat(a.getRunningHours())
                    .as("check runningHours")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getRunningHours())
            )
            .satisfies(a ->
                assertThat(a.getPowerOutput())
                    .as("check powerOutput")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPowerOutput())
            )
            .satisfies(a ->
                assertThat(a.getAverageRpm())
                    .as("check averageRpm")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAverageRpm())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMachineryOperationLineUpdatableRelationshipsEquals(
        MachineryOperationLine expected,
        MachineryOperationLine actual
    ) {
        assertThat(actual)
            .as("Verify MachineryOperationLine relationships")
            .satisfies(a -> assertThat(a.getEventReport()).as("check eventReport").isEqualTo(expected.getEventReport()));
    }
}
