package com.falaisia.ship.eventreporting2.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PortAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPortAllPropertiesEquals(Port expected, Port actual) {
        assertPortAutoGeneratedPropertiesEquals(expected, actual);
        assertPortAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPortAllUpdatablePropertiesEquals(Port expected, Port actual) {
        assertPortUpdatableFieldsEquals(expected, actual);
        assertPortUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPortAutoGeneratedPropertiesEquals(Port expected, Port actual) {
        assertThat(actual)
            .as("Verify Port auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPortUpdatableFieldsEquals(Port expected, Port actual) {
        assertThat(actual)
            .as("Verify Port relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getUnlocode()).as("check unlocode").isEqualTo(expected.getUnlocode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPortUpdatableRelationshipsEquals(Port expected, Port actual) {
        // empty method
    }
}
