package com.falaisia.ship.eventreporting2.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShipAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipAllPropertiesEquals(Ship expected, Ship actual) {
        assertShipAutoGeneratedPropertiesEquals(expected, actual);
        assertShipAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipAllUpdatablePropertiesEquals(Ship expected, Ship actual) {
        assertShipUpdatableFieldsEquals(expected, actual);
        assertShipUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipAutoGeneratedPropertiesEquals(Ship expected, Ship actual) {
        assertThat(actual)
            .as("Verify Ship auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipUpdatableFieldsEquals(Ship expected, Ship actual) {
        assertThat(actual)
            .as("Verify Ship relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCallSign()).as("check callSign").isEqualTo(expected.getCallSign()))
            .satisfies(a -> assertThat(a.getIceClassPolarCode()).as("check iceClassPolarCode").isEqualTo(expected.getIceClassPolarCode()))
            .satisfies(a ->
                assertThat(a.getTechnicalEfficiencyCode())
                    .as("check technicalEfficiencyCode")
                    .isEqualTo(expected.getTechnicalEfficiencyCode())
            )
            .satisfies(a -> assertThat(a.getShipType()).as("check shipType").isEqualTo(expected.getShipType()))
            .satisfies(a ->
                assertThat(a.getMonitoringMethodCode()).as("check monitoringMethodCode").isEqualTo(expected.getMonitoringMethodCode())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipUpdatableRelationshipsEquals(Ship expected, Ship actual) {
        assertThat(actual)
            .as("Verify Ship relationships")
            .satisfies(a -> assertThat(a.getOwnerCountry()).as("check ownerCountry").isEqualTo(expected.getOwnerCountry()))
            .satisfies(a -> assertThat(a.getFlag()).as("check flag").isEqualTo(expected.getFlag()))
            .satisfies(a ->
                assertThat(a.getClassificationSociety()).as("check classificationSociety").isEqualTo(expected.getClassificationSociety())
            );
    }
}
