package com.falaisia.ship.eventreporting2.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VoyageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoyageAllPropertiesEquals(Voyage expected, Voyage actual) {
        assertVoyageAutoGeneratedPropertiesEquals(expected, actual);
        assertVoyageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoyageAllUpdatablePropertiesEquals(Voyage expected, Voyage actual) {
        assertVoyageUpdatableFieldsEquals(expected, actual);
        assertVoyageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoyageAutoGeneratedPropertiesEquals(Voyage expected, Voyage actual) {
        assertThat(actual)
            .as("Verify Voyage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoyageUpdatableFieldsEquals(Voyage expected, Voyage actual) {
        assertThat(actual)
            .as("Verify Voyage relevant properties")
            .satisfies(a -> assertThat(a.getNumber()).as("check number").isEqualTo(expected.getNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVoyageUpdatableRelationshipsEquals(Voyage expected, Voyage actual) {
        assertThat(actual)
            .as("Verify Voyage relationships")
            .satisfies(a -> assertThat(a.getShip()).as("check ship").isEqualTo(expected.getShip()));
    }
}
